// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElSpace: typeof import('element-plus/es')['ElSpace']
}
export {}
